name: 📦 Development Requirements
description: Suggest or document new dev requirements, features you would like to see
title: "[Dev Req] "
labels: [enhancement, requirements]
body:
  - type: textarea
    id: requirement-description
    attributes:
      label: Describe the new requirement
      description: Please describe new dev requirement -  What new action/feature or enhancements to existing action/feature do you want cdp-airflow-provider to provide and why?
    validations:
      required: true

